apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- microservices-analysis.yaml
- scaler.yaml

namespace: business
images:
- name: microservices-analysis
  newName: binesty.azurecr.io/microservices-analysis
  newTag: 0.2.0-alpha.13
