apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- microservices-analysis.yaml

namespace: workspace
images:
- name: microservices-analysis
  newName: binesty.azurecr.io/microservices-analysis
  newTag: a5b5da78f9521cb252130e833918ccf37d555ddb
