apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- microservices-analysis.yaml
- scaler.yaml

namespace: workspace
images:
- name: microservices-analysis
  newName: binesty.azurecr.io/microservices-analysis
  newTag: 8206e923508579570ec35017aaee4ee89c2753e1
