apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- microservices-analysis.yaml
- scaler.yaml

namespace: workspace
images:
- name: microservices-analysis
  newName: binesty.azurecr.io/microservices-analysis
  newTag: 0.0.1-main.1.368d7c8
