name: pipelines
on:
  push:
    branches:
      - development 

jobs:
  build:  
    runs-on: ubuntu-latest
    name: build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Authorise NuGet
      uses: StirlingLabs/GithubNugetAuthAction@main
      with:
        owner: ${{github.repository_owner}}
        name: Packages-Microservices
        token: ${{secrets.TOKEN_PACKAGES_READ}}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration release



  test:
    runs-on: ubuntu-latest
    name: test
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Test
      run: dotnet test --no-build --verbosity normal



  release:
    runs-on: ubuntu-latest
    name: release     
    needs: test
    steps:
      - name: Chekout
        uses: actions/checkout@v3

      - name: Authorise NuGet
        uses: StirlingLabs/GithubNugetAuthAction@main
        with:
          owner: ${{github.repository_owner}}
          name: Packages-Microservices
          token: ${{secrets.TOKEN_PACKAGES_READ}}

      - name: Set MyProject.csproj version
        id: update
        uses: Thundernerd/dotnet-project-version-updater@v1.2
        with:
          file: "source/Microservices.Analysis/Microservices.Analysis.csproj"
          version: ${{ github.event.inputs.version }}

      - name: Publish project with version
        run: dotnet publish --version-suffix=development /t:PublishContainer -c Release

      - name: Docker Login
        uses: actions-hub/docker/login@master
        env:
          DOCKER_REGISTRY_URL: binesty.azurecr.io
          DOCKER_USERNAME: ${{ secrets.REGISTRY_USER }}
          DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Tag built container with Azure Container Registry
        uses: actions-hub/docker/cli@master
        with:
          args: tag microservices-analysis:latest binesty.azurecr.io/microservices-analysis:${{ github.event.inputs.version }}
      
      - name: Push built container to Azure Container Registry
        uses: actions-hub/docker/cli@master
        with:
          args: push binesty.azurecr.io/microservices-analysis:${{ github.event.inputs.version }}

      - name: Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image tag version
        run: |
          cd kubernetes
          kustomize edit set image microservices-analysis=binesty.azurecr.io/microservices-analysis:${{ github.event.inputs.version }}

      - name: Commit changes version 
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "${{ github.actor }}"          
          git commit -am '${{ github.event.head_commit.message }} - update image version and project'
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: development