name: pipelines
on:
  push:
    branches:
      - development 

jobs:
  build:  
    runs-on: ubuntu-latest    
    name: build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x        

    - name: Restore dependencies
      run: dotnet restore --source https://nuget.pkg.github.com/binesty/index.json --api-key ${GITHUB_TOKEN}

    - name: Build
      run: dotnet build --no-restore --configuration release


  test:
    runs-on: ubuntu-latest
    name: test
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Test
      run: dotnet test --no-build --verbosity normal 